### ISSUE TITLE
Time and reverse time

### ISSUE THREAD

**Issue by SirOttomano** [SrNetoChan/WalkingTime#6]
Hi Neto, my compliments for this very useful plugin. I would like to ask  a question about the fields "time" and "reverse time". Is the field time (forward direction) from the lowest slope to the highest slope? 

Thank you,
Giovanni

**Comment by SrNetoChan** [comment]
Ciao Giovanni,

"Is the field time (forward direction) from the lowest slope to the highest slope?"

Not really. Time and reverse time are not related with the direction of the slope to the slope (notice that the same line feature can cross several ups and downs in the elevation), but with the feature's line direction.

Therefore, time refers to the estimated travel time, following the line digitizing direction, while reverse time refers to the oposit direction. 

Depending on the way you will use the results, you may need to visualize and reverse some line directions. 

To visualize the line direction, you can use marker symbols with arrows. To reverse a line direction, you can use one of the tools of the digitizing tools plugin.

**Comment by SirOttomano** [comment]
Hi Alexandre,

Thank you very much for your answer. If I understood well, the travel time is based both on the Tobbler’s hiking function and on the line digitizing direction.  In my research, I need to evaluate the travel time along a pedestrian route that I drawn some months ago, and currently I don't remember the line digitizing direction.
Please, could you indicate me the QGIS tool for visualizing the line direction?

**Comment by SrNetoChan** [comment]
Hi giovanni,

You understood well. Like I said before, the best way to check the line direction is to have some arrow markers to you line style. I found this blog that speaks about that, maybe it will help you understand how you can do it.

https://woostuff.wordpress.com/2012/07/22/qgis-style-tricks-using-styles-to-help-fix-kerb-line-directions/
